### ISSUE TITLE
Provide guidance when the network is not yet ready for interaction.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1081]
UI Version: 0.9.3

Description:

On the Staking page I see a list of validators but no way to interact with them.

<img width="1020" alt="screen shot 2018-08-06 at 12 20 22 pm" src="https://user-images.githubusercontent.com/2148537/43728459-2baf0fa6-9973-11e8-803d-2e108913e4e7.png">

**Comment by nylira** [comment]
It looks like you've joined gaia-7005, which did not start generating blocks yet, as of 14 hours ago. As of now, blocks are being generated and I can see the checkboxes for selection validators now. Can you confirm?

It sounds like the proper solution to this issue is to show somewhere that the network has not reached the 67% staked atoms marker yet, and you cannot interact with the network until that point.

**Comment by faboweb** [comment]
Great idea. @nylira can you create an issue recommending this?

**Comment by jbibla** [comment]
we gotta get luigi under control

![tenor](https://user-images.githubusercontent.com/6021933/43779502-8b262f92-9a26-11e8-90b0-ba22253374b6.gif)

**Comment by jbibla** [comment]
you won't see checkboxes if you don't have any steak. not a great solution. let's just remove that v-if and let the user check all the boxes they please.

**Comment by faboweb** [comment]
@jbibla can you create an issue recommending this, or @NodeGuy we retitle this issue

**Comment by NodeGuy** [comment]
I had steak.

I retitled the issue.

**Comment by jbibla** [comment]
yes, it appears that _not_ having steak was _not_ the issue

**Comment by NodeGuy** [comment]
Oops, now I realize that I didn't have steak and that Voyager was incorrectly showing steak in my wallet because of https://github.com/cosmos/voyager/issues/1112.

**Comment by jbibla** [comment]
this issue cannot be reproduced _and_ we will implement the new designs next sprint.
