### ISSUE TITLE
Staked Balances but no validators are staked.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1106]
UI Version: 0.9.3

Description:
<img width="795" alt="screen shot 2018-08-08 at 1 33 00 pm" src="https://user-images.githubusercontent.com/2148537/43853983-9adf39e4-9b0f-11e8-977c-a1099718ffdc.png">
<img width="986" alt="screen shot 2018-08-08 at 1 33 28 pm" src="https://user-images.githubusercontent.com/2148537/43854121-f7728b02-9b0f-11e8-8f59-3bbbd3a2dd33.png">

It's possible that the wallet balances were carried over by mistake during the transition from 7004 to 7005.

**Comment by jbibla** [comment]
this is probably a duplicate of https://github.com/cosmos/voyager/issues/1110

could be caused by storing state in local storage without mention of the network name - as you brought up in slack.

could also be because voyager was never actually released for 7005 - it just "worked" because we didn't have to update the binaries. it's a different genesis file and network name and still needs a separate release.

**Comment by NodeGuy** [comment]
Closing in favor of https://github.com/cosmos/voyager/issues/1112.
