### ISSUE TITLE
Add new transaction designs

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1191]
We want the new design of the transactions to appear in the tx history list of Voyager. This probably means using the https://github.com/tendermint/ui/tree/develop/src/components/TmLiAnyTransaction component.

**Comment by okwme** [comment]
https://sketch.cloud/s/xKnxA/all/voyager-ui/

**Comment by faboweb** [comment]
Updated the description for a better scope def.

**Comment by okwme** [comment]
![image](https://user-images.githubusercontent.com/964052/44786728-50ddf380-ab95-11e8-8cda-a211248c6561.png)

This the most recent image i can find. Unsure whether it is final because of the discussion about circle versus text being colored.

Types of txs I see here w their associated metadata:

1. Send
   * amt
   * to
   * time
   * block
   * totalAtoms - at time of sending?
2. Receive
   * amt
   * from
   * time
   * block
   * totalAtoms - at time of sending?
3. Stake
   * amt
   * to
   * time
   * block
   * totalAtoms - at time of sending?
4. Unstake
   * claim date
   * amt
   * from
   * time
   * block
   * totalAtoms - at time of sending?
5. Claim
   * amt
   * from
   * time
   * block
   * totalAtoms - at time of sending?
6. Restaked
   * amt
   * to
   * from
   * time
   * block
   * totalAtoms - at time of sending?
7. Direct Vote
   * proposal
   * time
   * block
   * totalAtoms - at time of sending?
8. Vote
   * proposal
   * by
   * time
   * block
   * totalAtoms - at time of sending?
9. Submitted
   * proposal
   * deposit (?
   * more?


Scope:
- [ ] Clarify Designs and terms
  - [ ] what is totalAtoms?
  - [ ] do transactions have blocknumber and time already?
  - [ ] do we color text or icons?
  - [ ] is there more data needed for "Submitted"? (it was cut off in the design)
- [ ] Replace current components `TmLiTransaction` and `TmLiStakingTransaction` with numbers 1–4
- [ ] Add styles for types 5-9 with dummy data
- [ ] Add filtering tabs for type groups

**Comment by faboweb** [comment]
> do transactions have blocknumber and time already?

yes

>  is there more data needed for "Submitted"? (it was cut off in the design)

let's focus on the transactions we currently use and add others later

**Comment by okwme** [comment]
Keeping my previous comment for reference but reducing scope of issue to the following:
- [ ] import tx components from `tendermint/ui`
- [ ] "hydrate" them
- [ ] bonus: tab filtering
- [ ] make designs 5-9 in the `tendermint/ui`
