### ISSUE TITLE
User Feedback: Hugh (staking)

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1269]
split from #1117 

- font too small!
- your votes (screenshot below) bug with count (your votes is greater than total votes)
- status = revoked - should be mentioned in the tooltip
- didn’t see next button after clicking checkboxes - didn't find "staking" screen
- wtf is unbounded steak (sounds like pulled pork) 🐷 
- maybe call “steak” “testnet-atoms” instead of steak?  _Looks like this won't happen: https://github.com/cosmos/testnets/issues/67_
![image](https://user-images.githubusercontent.com/6021933/43925439-3e4a74f0-9bf5-11e8-8149-47cadb41e542.png)

**Comment by NodeGuy** [comment]
@jbibla Some questions:

- font too small!
- didn’t see next button after clicking checkboxes - didn't find "staking" screen

Are these no longer relevant because of your new designs?

> status = revoked - should be mentioned in the tooltip

What does that mean?

**Comment by jbibla** [comment]
> Are these no longer applicable because of your new designs?

i've tried to use larger font sizes and it seems like avoiding the checkboxes will resolve the other issue.

---

the second question is no longer relevant because there will not be a filter for status' and therefore no corresponding tooltip. but what that meant was that if you hover on the status filter you will see a tooltip with description of status - but it doesn't mention `revoked` as an option.

**Comment by faboweb** [comment]
@jbibla can close this?

**Comment by jbibla** [comment]
yep. these concerns have been addressed.
