### ISSUE TITLE
LiDelegate watcher bug/refactor

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1276]
in `LiDelegate.vue:87` we're using a watcher on a getter  to trigger a mutation. The unit tests don't cover this scenario, which pointed the code out. I don't think this should be handled this way, and also is probably the culprit for the bug where you show a staked delegegator with the locked checkbox, yet you can't click next because they're not actually in the shopping cart.
````
  watch: {
    yourVotes(newVal) {
      if (newVal > 0) {
        this.$store.commit("addToCart", this.delegate)
      }
    }
  }
````

**Comment by NodeGuy** [comment]
Please remove issues from the backlog when moving them into Scrumptious.

**Comment by NodeGuy** [comment]
> The unit tests don't cover this scenario, which pointed the code out.

What does that sentence mean?  I'm having trouble parsing it.

**Comment by faboweb** [comment]
a watcher shouldn't probably call a commit on the store as it is not an interaction. this looks like a bad fix to solve the problem that not always all committed validators are present in the `shoppingCart`. Making sure of this should probably be handled in the store. this might already be fixed.

there strangely was no test coverage for this watcher. we decided to not create the coverage as we identified the to be covered code as wrong.

scope of this issue:
- remove the wrong code
- check if there are any undesired side effects because of the removal of that code
- fix those side effects
