### ISSUE TITLE
refactor / update language to match current understanding + terminology

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1283]
i would _LOVE_ if we refactored just the language because delegates and delegators feels very old and unfamiliar.

the main issue i noticed was `delegates` and `delegators` but surely there are many others.

**Comment by NodeGuy** [comment]
What is our current understanding + terminology?

**Comment by faboweb** [comment]
delegates = candidates = validators. we agreed on naming them validators.
delegators stays the same as far as I know.

**Comment by jbibla** [comment]
well, the current conversation is that we want to push `Bonded Proof of Stake` which according to made up rules about language would imply that delegators = bonders. fun fact, roberta bondar 👩‍🚀  was the first canadian astronaut.

here are some combinations i've seen. feel free to add some if they are missing. i think the strongest choice is the last row to support `BPoS` and current (relatively) well understood terminology.

| verb  | (ad)verb | atom holders | validators & candidates |
| ------------- | ------------- |  ------------- | ------------- |
| delegation | unbonding  | delegator  | delegates  |
| bonding  | unbonding | bonders  | validators |
| staking | unstaking | stakers | validators |
| bonding | unbonding | atom holders | validators |

@rigelrozanski @jackzampolin what do you think?

**Comment by rigelrozanski** [comment]
bonding should generally never be used to describe an action of an actor, `bonded`, `unbonded`, and `unbonding` should only be used to describe the state of atoms, which is somewhat independent of whether tokens are `delegated` or `undelegated`. `delegating`, `undelegating` or `redelegating` are the actions which delegators (and validators) may make. 

I would also totally avoid the language of `stake` or maybe it should be used to replace the term `bond` - but if that's the case we should be consistent everywhere (right now we are consistently not using `stake` in the sdk).

**Comment by jbibla** [comment]
> bonding should generally never be used to describe an action of an actor

what is the thinking here?

> delegating, undelegating or redelegating are the actions which delegators (and validators) may make.

sure, but in a BPoS system wouldn't it make sense to use Bonding and associated terminology instead of delegation - which is a lot like "Delegated Proof of Stake" which we are intentionally trying to distance ourselves from?

> we should be consistent everywhere

100% - this is the impetus for this ticket now, i guess.

**Comment by Chjango** [comment]
I might even suggest going up a level higher. As far as describing our consensus mechanism in one elegant acronym like BPOS, we may not even have to change the underlying associated verbiage like who "delegators" are or who does the "bonding/delegating" action. This change _could_ be as simple as classifying ourselves as BPOS when we speak at conferences and meetups and popularizing it that way. We can avoid complicating/bikeshedding about what to change at the level of granularity we're currently discussing right now. For all intents and purposes, BPOS is a marketing terminology. Nothing more. I recommend against refactoring all of our documentation and making people relearn all but one new terminology we come up with. The one being: BPOS.

Here's what's happening in the development landscape. Even seasoned blockchain developers (people who have been doing stuff in crypto for 3+ years) don't have a word for differentiating between those masternode PoS protocols and Cosmos'. Meaning, there is _no word_ out there classifying this particular class of PoS security. Without one, **we risk being diluted, conflated, and bucketed into the same category of naive, simple-to-implement PoS protocols** like that of DASH, PIVX, EOS, and all those other ones that don't do nearly _half_ the things they promise that we actually deliver in Cosmos.

I'm beating a dead horse at this point but this point needs to get across to everybody again and again to help people understand the whole point of this exercise: **This is because Cosmos' PoS implementation is the _only one in the world_ right now that is coming-to-production with in-protocol slashing.** Casper is the only other thing that promises this. Yet they have no such implementation even near ready. This means that if we get this _one thing_ right, helping the general population understand _this very significant point_ with a _single word_ will effectively be **our claim to fame**. This is what Cosmos should be known for.

Because all other PoS implementations coming after us are going to be using our libraries basically, if Cosmos fails in the PoS design space, then the whole space fails. If Cosmos can't get PoS right, then others have no hope of getting it right either. That's how big this is. That's how bleeding edge we are in terms of pioneering this thing. And other projects are trying to claim this right. No. This is _our_ claim. We need to **take it** and coming up with the right acryonym to do it is a good step in that direction.

With that in mind, I really don't think we should put so much focus on the other jargon. This is needed just to classify our consensus algorithm and what it does in one acronym that encompasses all that ^^ was written above.

**Comment by rigelrozanski** [comment]
> what is the thinking here? 

The word "bond" is quite overloaded in our system so to avoid confusion we must separate out into multiple terms. 

https://github.com/cosmos/cosmos-sdk/issues/1879

> sure, but in a BPoS system wouldn't it make sense to use Bonding and associated terminology instead of delegation - which is a lot like "Delegated Proof of Stake" which we are intentionally trying to distance ourselves from?

Is there consensus on switching the lingo for us to be using BPoS? that's the first I'm hearing of this. But also I disagree, I don't see why it's any different whether we're called "BPoS" or "DPoS" there is still the concept of token state (`bonded`/`unbonded`/`unbonding`) and attribution (`delegated`/`undelegated`) - so it's really all the same, I don't care if we choose to swap language so much, however it's very important that we maintain distinct terms between state and attribution as I just explained. 

______________________________________________
@Chjango 

Couldn't agree more with your points 👏

**Comment by Chjango** [comment]
> I don't see why it's any different whether we're called "BPoS" or "DPoS" there is still the concept of token state...

Technically, like you said, there is no difference. Marketing-wise, DPoS is EOS's claim to fame and if we use DPoS, we risk the dilution, conflation, and bucketing with EOS's system in the eyes of the lay person. So BPoS is our attempt to clarify the distinction, despite using the same word for attribution at the protocol level.

**Comment by fedekunze** [comment]
@jbibla here's my proposal:

Actions:

`staked`,`bonded` --> `delegated` or `redelegated` depending on the type
`staking` --> `delegation` or `redelegation` depending on the type

`delegate` --> `validator`

**Comment by jbibla** [comment]
| verb  | (ad)verb | atom holders | validators & candidates |
| ------------- | ------------- |  ------------- | ------------- |
| delegation | unbonding  | delegator  | validators  |

**Comment by rigelrozanski** [comment]
CC @fedekunze @jbibla 

ahahaahaha - THIS IS MESSY - Everyone should make sure they understand the following breakdown. 
I'd suggest the UI adopt this language verbatim: 

- Tokens (owned by either a validator or a deleator) can have one of the three states:
  - `bonded`, `unbonded`, or `unbonding`
- In _addition_ to this attribute, tokens which are owned by a delegator can also be 
  - `delegated` or `undelegated`
- Delegators tokens can be held in the following objects:
  - Their wallet
  - A `delegation` - (holds shares representing tokens in a validator)
  - A `redelegation` - (holds shares representing how many tokens _would_ have been in the original validator, the actual tokens are held in the new validator with a new `delegation` object)
  - An `unbonding-delegation` - (holds the actual tokens)

**Comment by faboweb** [comment]
I vote for @fedekunze proposal.
Let's drop `bonding` and only use forms of `delegation`. I don't think the users need to be confused by 2 different verbs/attributes. I can't see a benefit for the user here. Can anyone point me to a benefit?

**Comment by faboweb** [comment]
To clarify: I can have delegated tokens to a validator that are currently unbonded from that validator because this validator (candidate) is not in the list of validators right now because he hasn't accumulated enough delegated tokens?
When are tokens in this scenario `unbonding`? I thought this happens instant?

**Comment by jbibla** [comment]
> THIS IS MESSY

yes. can we make it _less messy_?

**Comment by rigelrozanski** [comment]
> can we make it less messy

I think the language I've laid out is pretty concise and clean. Just use that! (if you understand it of course) - I was referring how you guys have been talking about some of these terms before, sometimes ambiguously or incorrectly - I don't like the idea of breaking things down into "verb/adverbs"s etc. kind of arbitrary doesn't actually what it's a verb of. Any action should be in reference to the affected objects - I think discussing these concepts a bit more verbosely with more context will lead to less confusion

_______ 
RE @faboweb 

Your first statement is close to being correct but the languages Incorrect, tokens have an `bond` state only as an attribute to the network, not "in reference to" a validator. Tokens can only be `delegated` or `undelegated` in reference to a validator. 

your statement would be correct if it was worded as followed:
    I can have delegated tokens to a validator that are currently **in the unbonded state** because this validator is not in the list of validators right now because he hasn't accumulated enough delegated tokens?

> When are tokens in this scenario unbonding? I thought this happens instant?

For tokens to move from the unbonding state to the unbonded state always takes the duration of the unbonding period (3 weeks). 

Undelegation or redelegation can be thought of as instant transactions, however the tokens are actually still locked, they are moved from the delegation object to a new unbonding/redelegation object **for the duration of the unbonding period**. During this period you are still liable to being slashed for malicious events which occured in the past if your voting power contributed to those events. 

CLARITY in use of language between the concept of _bonding_ and _delegating_ is KEY and we should all refine our use to be more concise between these two distinct concepts. 

The following are all correct statements which can occur on the hub: 
 - "tokens are in the bonded state and also delegated to a validator" 
 - "tokens are in the unbonding state and also delegated to a validator" 
 - "tokens are in the unbonded state and also delegated to a validator" 
 - "tokens are in the unbonding state and also undelegated to a validator" 
 - "tokens are in the unbonded state and also undelegated to a validator" 

The following is a situation which could NEVER occur on the hub:
  - "tokens are in the bonded state and also undelegated to a validator" 

Additionally here is a statement which doesn't make any sense based on the language as explained and should not be used:
 - "tokens are bonded/unbonded/unbonding to a validator" 
The correct statement to describe the same thing is:
 - "tokens are delegating/undelegating to a validator"

**Comment by jbibla** [comment]
very helpful. thank you @rigelrozanski.

- what do you call atom hodlers?
- what do you call the group that includes validators _and_ candidates?

**Comment by fedekunze** [comment]
We should add this to the SDK FAQ

**Comment by rigelrozanski** [comment]
@jbibla - good Qs

> what do you call atom hodlers?

as in somebody who is not engage in any of the delegation/validation stuff at all? Not totally sure, probably just that `atom hodlers`/`non-delegators`/`non-bonders` or maybe `outsiders` or `weak souls` JKS 

> what do you call the group that includes validators and candidates?

Candidates is an old concept which should generally not be used. There are only validators thus in your context the group which includes "validators and candidates" should just be named **The Validators**. From here if you want to refer to the kids actually running Tendermint and the network you should refer to **The Bonded Validators**

**Comment by jbibla** [comment]
i'm not convinced yet that it makes sense for us to keep staking, delegation, and bonding around. do we need all three categories and their variations?

**Comment by rigelrozanski** [comment]
testnet token - arbitrary/don't matter
as for the module name and lcd paths - we could consider renaming it - (see thoughts here https://github.com/cosmos/voyager/issues/1365#issuecomment-425149579)

**Comment by jbibla** [comment]
what do you mean @NodeGuy ?

**Comment by NodeGuy** [comment]
I'd like to know what language we should be using without having to a get a PhD.  😃

**Comment by jbibla** [comment]
me too 😭

**Comment by faboweb** [comment]
In the context of the UI we more or less can ignore the terminology of `bonded` tokens. A user only cares about if he has liquid tokens not `delegated` to a validator, tokens currently `delegated` to a validator and not usable tokens he started `undelegating` from a validator. `redelegating` happens instant and therefor is not a state just an action.
This is how I understand it.

**Comment by ebuchman** [comment]
what if the bonding language became more like "active/inactive/inactivating"? then it would be "active delegation" instead of "bonded delegation"

**Comment by ebuchman** [comment]
>  A user only cares about if he has liquid tokens not delegated to a validator, tokens currently delegated to a validator and not usable tokens he started undelegating from a validator.

This makes sense - we should try to tailor the language more towards what the user actually has to think about / interact with rather than what might be going on deeper in the state machine

**Comment by rigelrozanski** [comment]
Yeah I suspect there _IS_ some better language which can be used which is less cumbersome while still correct - just need to pin it down - on that note I take back that we _need_ to use `bonded validators` - there's likely correct alternatives, however `undelegated validator` is by definition incorrect and highly confusing for me. 

We're setting up a phone discussion for I believe thursday to discuss more

_______
@ebuchman 
> we should try to tailor the language more towards what the user actually has to think about / interact with rather than what might be going on deeper in the state machine

Agreed, however we should _also_ not mislead the user into thinking something which is false about how the system operates, delegators are going to need some basic level of competency in understanding what and how cosmos's D-B-POS system functions. 

hmm so are you suggesting a third set of terms `active/inactive/inactivating` to take over the language of both `delegated/undelegated/undelegating` and `bonded/unbonded/unbonding`? 
... I think I kinda like this!!!!! - going to sit on it a tiny bit more, maybe there is a better noun than `active` per say, and we would also want a hyper-explicit document explaining the relationship between the three nouns... but I think you're onto something great :)

**Comment by rigelrozanski** [comment]
How about `locked/unlocked/unlocking`? I like this because it also describes a clear attribute about what you can do with those tokens. This is how it translates (you could also replace `lock` with `active` here)

"bonded validator" -> "locked validator"
"unbonded validator" -> "unlocked validator"
"unbonding validator" -> "unlocking validator"

 "tokens are in the bonded state and also delegated to a validator"  -> "locked delegation"
 "tokens are in the unbonded state and also delegated to a validator"  -> "unlocked delegation"
 "tokens are in the unbonding state and also delegated to a validator" -> "unlocking delegation"
 "tokens are in the unbonding state and also undelegated to a validator" -> "unlocking wallet tokens"
 "tokens are in the unbonded state and also undelegated to a validator" -> "unlocked wallet tokens"

Thoughts?
