### ISSUE TITLE
Duplicate keys on mystake page

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1364]
The keys need to be prefixed as a validator may be in both lists:

![image](https://user-images.githubusercontent.com/5869273/46092551-64d93d00-c1b5-11e8-8323-ea73b0505ba5.png)

**Comment by jbibla** [comment]
i don't think the validator should appear in both lists. i think we should filter out the unstaked validators from the top list.

**Comment by faboweb** [comment]
Why? I could have stake with a validator and am unstaking from him at the same time.

**Comment by jbibla** [comment]
do you mean you may stake 500 atoms to validator x and then later unstake 250 from that same validator ... and therefore validator x would have to appear on both lists? 

that makes sense - i hadn't considered that scenario.

this means we should really show _how many atoms_ the user has unbonded from validator x - and also the unbonding period. 


just a thought... should we display the unbonding tx in the second list instead of the validator Li?

**Comment by faboweb** [comment]
> just a thought... should we display the unbonding tx in the second list instead of the validator Li?

This sounds like a good idea. :)

**Comment by NodeGuy** [comment]
It's hard to recreate this bug now that undelegation is unavailable.  Blocked by #1294.

**Comment by faboweb** [comment]
This is unblocked
