### ISSUE TITLE
Can’t increase amount to undelegate (add the number) when 0 < bond < 1 

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1409]
Follow up of https://github.com/cosmos/voyager/pull/1367#pullrequestreview-161516834

**Comment by NodeGuy** [comment]
I tried to replicate this by bonding 0.5 Steak but Voyager wouldn't let me (`Confirm Delegation` is disabled).  Is that expected behavior?

**Comment by faboweb** [comment]
Currently it is. Delegation transactions only allow for whole numbers to be delegated.

**Comment by jbibla** [comment]
> Delegation transactions only allow for whole numbers to be delegated.

what is the reason?

**Comment by faboweb** [comment]
> what is the reason?

apparently this is due to the fact, that there will be no `fractions of atoms`. we will only have `sub-atoms` (1:1000000000) and users will loose fractions of `sub-atoms` in certain scenarios. we then delegate `sub-atoms`.

**Comment by faboweb** [comment]
@fedekunze could you quickly help with clarify what the original issue was you filed?

**Comment by fedekunze** [comment]
It’s more like because the input field only increases the step by 1 using the up button, if you have < 1 atom due to slashing you won’t be able to do anything, only typing the exact amount you want to undelegate. 

The ideal situation is that the inputs field increases the step by 1 (step=1) until you reach floor(maximum) and then change the step to decimal in order to be able to unbond your ‘maximum’ specified amount

**Comment by fedekunze** [comment]
@faboweb @NodeGuy Do we want to be able to delegate, redelegate and unbond `subatoms` ?

**Comment by faboweb** [comment]
yes the user should be able to delegate, redelegate and unbond subatoms. the concern before was that delegating fractional atoms (or subatoms) is not possible.
