### ISSUE TITLE
do we need to add a route named 'block'?

### ISSUE THREAD

**Issue by coreycosman** [cosmos/voyager#1915]
UI Version: 0.X.X

Description:

I have questions and don't know where else to have them fielded but here. I hope opening an issue for this is not a problem, if it is, please point me in the direction of where I can ask people specfic questions:

I am working on an old issue: []((https://github.com/cosmos/voyager/issues/1778))

I am in the process of writing a spec for the `goToBlock` method on `TmModalSearch.vue`:

```
    gotoBlock() {
      this.$router.push({
        name: `block`,
        params: { block: this.filters.blocks.search.query }
      })
```

 In my spec I am doing this:

```
wrapper.vm.type = `blocks`
wrapper.vm.filters.blocks.search.query = `test input`
wrapper.vm.gotoBlock()
expect(wrapper.vm.$route.name).toEqual(`block`)
```
 
It seems that this should work. However, this route does not seem to exist:  `[vue-router] Route with name 'block' does not exist`

Am I missing something here, or do we need to add this route?

**Comment by jbibla** [comment]
hello @coreycosman! no problem - this is an ok place to ask questions for now.

we used to have a block explorer and associated routes but we removed them from the app. i am actually working on bringing them back this week. however, i am not sure we are actually using TmModalSearch anymore.

is there an open issue that sent you down this path? if so, please share here. otherwise i would advise sticking to the open issues. if you're interested in helping with tests a number of the tickets labelled "refactor" relate to the tests. or we can find something suitable.

**Comment by coreycosman** [comment]
sorry i meant to include this in my previous post [](https://github.com/cosmos/voyager/issues/1778)

I opened this issue a little over a month ago, at that time, I was running `yarn test:coverage` and seeking out files where it seemed appropriate to bump up the coverage: this one was a good candidate. If this approach no longer works (as it seems to not), I will close this issue, and begin to dig into every issue with a refactor tag, see how the coverage holds up on those specific files, and write additional tests where appropriate. My computer is currently in the shop so there will be a bit of a delay here. Thoughts?

**Comment by sabau** [comment]
Hi @coreycosman, thanks for the proactivity, I'll mark this as duplicat(ish)ed of:
https://github.com/cosmos/voyager/issues/1866

Even if the question was related to `TmModalSearch`
