### ISSUE TITLE
Handle ledger disconnection before signing

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1917]
What happens if the user signs in with ledger and then disconnects before he clicks to sign with ledger?
Should we show an additional note for this?
Is there a bug if this happens?

Scope:
- Check if Ledger is connected when opening ActionModal
- Reconnect if Ledger is not connected

**Comment by jbibla** [comment]
i don't think we should allow logins with ledger ... it is unnecessary since _signing_ is not actually required for "signing in".

**Comment by faboweb** [comment]
We get the address of the user from the ledger. I think it is the most efficient way for the user to provide Voyager with his address.

**Comment by jbibla** [comment]
ahhhhhhhhhhhhhhh. fair enough.

i suppose this is an added convenience. but this should only be needed on the first session per device if we are storing the addresses / accounts in local storage.

---

the ledger should be disconnected after sign in because the connection is not needed until transactions need to be signed. can we disconnect on purpose? users will be able to use the app without "signing in" anyways.

**Comment by faboweb** [comment]
>  but this should only be needed on the first session per device  if we are storing the addresses / accounts in local storage.

Great idea, but we need to rebuild/redesign sign-in for this.

**Comment by faboweb** [comment]
Updated scope

**Comment by fedekunze** [comment]
the part of `* Check if Ledger is connected when opening ActionModal` can be accomplished by changing the transport communication method with the ledger from `comm_u2f` to `comm_node`, but it is failing because of a library dependency error on `ledger-cosmos-js`. I already contacted Juan to push a fix soon
