### ISSUE TITLE
Pass COSMOS_NETWORK env var through in production build

### ISSUE THREAD

**Issue by mappum** [cosmos/voyager#304]
When building, we should be able to specify the `COSMOS_NETWORK` env var and have the built app bundle use this network. Instead, we currently have to change the default in `app/src/main/index.js`.

dependencies: #534

**Comment by NodeGuy** [comment]
If we're going to start the app with a local network by default then isn't this feature superseded by #27?

**Comment by faboweb** [comment]
This is a good point. The purpose of this issue was, to create a quick way to build Voyager for different networks without changing config files. I.e. for our demo in April or for developers that test their own blockchain. Do you think, that we will be able to integrate #27 and the whole process of switching from local to online before then?

**Comment by mappum** [comment]
Closed via #604
