### ISSUE TITLE
ux / usability notes (sasha)

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#500]
Windows 10

- Cosmos.exe
  - can we move these files away - confusing!!
  - on click, showed loading screen and then closed itself
  - text on welcome screen is too skinny, can be difficult to read
  - message about firewall came up re: cosmos & gaia
  - can’t click create new account
- fundraiser seed is off putting / scary / unknown info for most
- create new account — pencil??
- full screen breaks / distorts
- separate message about gaia is off putting uncomfortable - no one knows this is related
- no positive first impression 
  - first thing seen is dark
  - then red warning sign
  - nothing friendly, nice, welcoming
- couldn’t click on anything until user gave permission to firewalls / alerts etc…

- could provide more direction for users
  - what to do with seed? copy and paste? write it down? some will want more info
- balance not refreshing from faucet
- delegates not loading
- ni-connectivity not incrementing

**Comment by nylira** [comment]
Re: text on welcome page, I think that on Windows we have to use a different font weight. 300 looks good on macOS retina displays, but it's too thin (like 1 pixel? on windows with low dpi).

**Comment by nylira** [comment]
> can we move these files away - confusing!!

We're working on an installer instead of a zip if you meant all the files in the zip.

> on click, showed loading screen and then closed itself

Strange, have to debug this.

> text on welcome screen is too skinny, can be difficult to read

Mentioned above ^

> message about firewall came up re: cosmos & gaia
> can’t click create new account

This is always going to happen on an OS with the firewall enabled. If the user has a firewall enabled they should know that these messages will pop up whenever they open an app that connects to the internet.

> fundraiser seed is off putting / scary / unknown info for most

It's supposed to be offputting and scary. This is a testing version of the UI and we don't want anyone to input their seed.

> create new account — pencil??

We can use a different icon.

> full screen breaks / distorts

Screenshot this for us? I haven't seen anything like it.

> separate message about gaia is off putting uncomfortable - no one knows this is related

Ah the second firewall message. I don't think we have any way around this.

> no positive first impression
> first thing seen is dark
> then red warning sign
> nothing friendly, nice, welcoming
> couldn’t click on anything until user gave permission to firewalls / alerts etc…

This is expected. We're not changing this currently.

> could provide more direction for users

We're working on this by adding an on screen tutorial.

> what to do with seed? copy and paste? write it down? some will want more info

The UI says to backup the seed, which means to make a copy in any way possible. I suppose we can add a longer description.

> balance not refreshing from faucet
> delegates not loading
> ni-connectivity not incrementing

Gaia issues. We're working on it.

**Comment by jolesbi** [comment]
> Strange, have to debug this. Do you mean on first load, the app closes itself for no reason?

yeah. on windows. was a bug that we thought we solved, but maybe didn't yet.

> no positive first impression
first thing seen is dark
then red warning sign
nothing friendly, nice, welcoming
couldn’t click on anything until user gave permission to firewalls / alerts etc…

This is expected. We're not changing this currently.

we should consider making it friendlier for launch 😄
