### ISSUE TITLE
How to Enter Seed after password is forgotten ?

### ISSUE THREAD

**Issue by azulmarino** [cosmos/voyager#637]
> Thank you for filing an issue!

### Version

Version 0.4.3 (0.4.3)

### Description

No clear indication of how to enter seed password when you forget password. Where is recovery "tab" ?
Also note issue 468 was closed without fix.
That is very useful , here we have one attempt to enter a pwd we cannot see and hope we have typed it as expected. Most systems now enforce password confirmation to check both fields.

**Comment by faboweb** [comment]
Importing seeds it feature flagged for now to prevent people from actually entering seeds for accounts that have value. Voyager is not properly security audited yet.
You can clone the repo and run Voyager as a developer to preview all features.

Issue #468 was closed because the implementation was completed in #532. 
There was no release since this implementation, but we aim to release early next week. So stay tuned!

Thank you for your feedback.

May I ask for which project you use Voyager for?

**Comment by azulmarino** [comment]
Hi ,

No I am an ICO investor. Just looking to play with Voyager and the Cosmos SDK . I have a technical background in databases , so just interested. 
Thanks
