### ISSUE TITLE
Onboarding tutorial shouldn't be checkbox in "My profile"

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#669]
### Onboarding tutorial shouldn't be checkbox in "My profile"
Click User account in bottom left
List of options are checkboxes
Clicking checkbox for "Onboarding tutorial"
I'd expect it to already be checked as in "Yes i've already seen the onboarding tutorial"
Instead it is unchecked, maybe checking it means yes skip it next time?
clicking it launches the onboarding screens, so really it's a button, not a checkbox at all

**Comment by jolesbi** [comment]
good call! it should probably be a normal checkbox indicating whether or not the user has completed the onboarding tutorial.

in the same line of thinking - "remote error tracking", "light theme", and "onboarding tutorial" could be more descriptive.

**Comment by nylira** [comment]
My thoughts on the entire Profile page:

<img width="770" alt="screen shot 2018-05-22 at 1 55 27 pm" src="https://user-images.githubusercontent.com/172531/40344553-d9180996-5dc7-11e8-9c64-4fb5773491a3.png">

* rename My Profile to Preferences
* remove account name, it's redundant with your account name in the bottom left corner
* remove address, this should be on the Balances page
* Remote error tracking sounds invasive, let's change this to "Automatically send usage statistics and crash reports to Cosmos" and use a toggle instead of checkbox
* Light theme should be relabeled "Theme", and we should have a toggle with two labels: Light and Dark.
* Onboarding tutorial's checkbox should be changed to a button with the label "View"
* Mock connection should be renamed "Server Connection". It should have a toggle with two labels, "Mock Server" and "Live Testnet".

**Comment by nylira** [comment]
And then to support #504, we could add another preference--letting the user input an IP address to connect to a specific full node.

**Comment by okwme** [comment]
"Automatically send usage statistics and crash reports to Cosmos" overflows in the current layout:

![screenshot 2018-05-23 15 34 26](https://user-images.githubusercontent.com/964052/40427748-e15f8246-5e9e-11e8-84ed-90a37fbf5bc7.png)

could be switched but also doesn't look very good: 
 
![screenshot 2018-05-23 15 34 57](https://user-images.githubusercontent.com/964052/40427763-e8c7ff7c-5e9e-11e8-89bc-3f917cdb59ae.png)

do we have a toggle/switch component for "Theme" somewhere already or should I make a new one or just use an existing one like:
 * http://vue-js-toggle-button.yev.io/
 * https://codepen.io/CSWApps/pen/YqZWwB
 * https://vuematerial.io/components/switch/
 * https://jsfiddle.net/adamwathan/hfs34ye4/
 * https://vuejsexamples.com/tag/switch/
