### ISSUE TITLE
Investigate why `PageSend.spec.js.snap` has `fields.amount` visible validation msgs

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#683]
### Version

0.6.0 (once #591 merges)

### Description

The file `test/unit/specs/components/wallet/__snapshots__/PageSend.spec.js.snap ` shows validation messages about send amounts even though the send button has not been pressed yet by the unit test.

https://github.com/cosmos/voyager/blob/7138a811263287af901e4b8376e2761feeb807aa/test/unit/specs/components/wallet/__snapshots__/PageSend.spec.js.snap#L762-L778

https://github.com/cosmos/voyager/blob/7138a811263287af901e4b8376e2761feeb807aa/test/unit/specs/components/wallet/__snapshots__/PageSend.spec.js.snap#L1626-L1642

**Comment by faboweb** [comment]
This is an expected behavior even though it is a bit confusing: The messages are there in the beginning with `display: none` and then the display property is overwritten when the first validation is called and the according form-group actually has an error. The `v-if` attributes are hiding all the messages that are fixed.
