### ISSUE TITLE
Disable node integration

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#712]
> Thank you for filing an issue!

### Version

Commit

### Description

![image](https://user-images.githubusercontent.com/5869273/40170706-72ff79b6-59c9-11e8-9048-13bf36d32c5a.png)

We have node integration enabled. Apparently this is a security risk. Currently Voyager doesn't run without it:

![image](https://user-images.githubusercontent.com/5869273/40170789-b59e52e2-59c9-11e8-9650-a96a84072ad3.png)

**Comment by nylira** [comment]
So I don't think this is a problem for us. There's a discussion here: https://github.com/electron/electron/issues/12049 The gist of it is that Electron is the wrong to tell us that localhost is insecure, and they've updated Electron 2.0+ to remove the warning for localhost connections.

The right solution for this issue is to upgrade to Electron 2.0.

**Comment by faboweb** [comment]
I vote then to spike upgrading to Electron 2.0
