### ISSUE TITLE
initial loading screen flashes white theme even when switching to dark theme on startup

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#764]
we should have the initial loading screen match whichever theme is the users preference.

**Comment by faboweb** [comment]
Thank you for adding this issue. I experienced this as well.

**Comment by okwme** [comment]
I actually didn't see any loading screen flashes (except for the app's loading screen which is always white). I did find that the theme switch wasn't getting saved to application state because the store was getting committed via v-model and a getter instead of a mutation that included persistent storage updates.

**Comment by nylira** [comment]
Good catch @okwme !

**Comment by jolesbi** [comment]
@okwme check this out too:
https://electronjs.org/docs/api/browser-window#showing-window-gracefully

**Comment by faboweb** [comment]
We need to set the whole color schema. Just the background will not be enough I guess.

**Comment by jolesbi** [comment]
i set the color in my PR #865 but there is another option where we can control when the window opens. like how slack handles it - you'll notice - they don't show a blank screen, they wait until the loading graphic is ready and they show that. no flash of blankness.
