### ISSUE TITLE
Staking sections self DDoSes

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#879]
UI Version: 0.7.0

Description: Polling each validator for amount of user's stake DDoSes the LCD and often crashes gaia causing a reconnect. This happens on mounted event for the staking page as well as wallet page with the action `updateDelegates`.

**Comment by mappum** [comment]
Update LCD to make it possible to do this in one combined request

**Comment by fedekunze** [comment]
@faboweb This could effectively be resolved by changing the endpoints we are using (latest delegator set + delegations for each of the address, which is what makes voyager self DDoS) for 
`GET /stake/validators` and
`GET /stake/delegators/{delegatorAddr}/validators` which is currently on hold by [cosmos-sdk/1939](https://github.com/cosmos/cosmos-sdk/issues/1939). 
I'll start working on it since it's a priority as discussed with @okwme .

**Comment by faboweb** [comment]
isn't this resolved by #1068 ?

**Comment by fedekunze** [comment]
No, since it's still querying every delegation instead of the delegator's validators

**Comment by fedekunze** [comment]
@faboweb this will reduce the requests to just 2 instead of running a for loop on all the addresses of the latest validator set to ask if there's a delegation
